---
name: test


on: pull_request

permissions: {}

jobs:
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@feat/first-pr
    with:
      aqua_policy_config: aqua-policy.yaml
      aqua_version: v1.32.3
      go-version: 1.19.5
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
    permissions:
      pull-requests: write
      contents: read # To checkout private repository
